name: 🗿🎀

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-puzzles:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: pip install zstandard

      - name: Run Fetch Script
        run: |
          cd crossword
          python fetch_puzzles.py
          cd ../chess
          python fetch_puzzles.py

      - name: Commit and Push
        run: |
          git config user.name "SunTzv"
          git config user.email "suntzu@ncrypt.net.in"
          git add crossword/todays/
          git add chess/todays/
          git commit -m "🗿🎀" || exit 0
          git push
